#
#  Python script to search all files and folders in a given directory
#  for a specified line of text.  if the line of text is found the full
#  file name is printed.
#

import sys, os
from time import localtime, strftime

# This function traverses the tree generated by os.walk, and checks
# each file line by line for the text 'search_text'.  If found, it
# prints the name of the file the text was found in and continues
def search(dir_root, search_text):
    s_cnt    = 0
    e_cnt    = 0
    p_cnt    = 0
    outfname = os.path.join(os.getcwd(),"text_search.log")
    outfile  = open(outfname, "a+", encoding='utf-8', errors='ignore')
    #if(os.path.exists(outfname)):
    #    outfile  = open(outfname, "a", encoding='utf-8', errors='ignore')
    #else:
    #    outfile  = open(outfname, "w", encoding='utf-8', errors='ignore')
    outfile  = open(outfname, "w", encoding='utf-8', errors='ignore')
    outfile.write("\n\n* " + strftime("%Y-%m-%d %H:%M:%S", localtime()) + "\n")
    outfile.write("* Began searching %s for %s" % (dir_root,search_text) + "\n")
    for root, dirs, files in os.walk(dir_root, topdown=False):
        for fname in files:
            try:
                file  = os.path.join(root,fname)
                f     = open(file)
            except PermissionError:
                #print("You do not have sufficient priveleges to open %s" % file)
                p_cnt += 1
            lines = []
            try:
                lines = f.readlines()
            except UnicodeDecodeError:
                #print("Error Decoding File")
                e_cnt += 1
            except UnicodeEncodeError:
                #print("Error Encoding File")
                e_cnt += 1
            except UnicodeError:
                #print("General Unicode Error")
                e_cnt += 1
            for line in lines:
                if(line.find(search_text) >= 0):
                    try:
                        #print("%s found in %s" % (search_text,file))
                        outfile.write("%s found in %s" % (search_text,file) + "\n")
                        outfile.write("\t%s\n\n" % line.encode('ascii','ignore'))
                        s_cnt += 1
                    except UnicodeDecodeError:
                        #print("Error Decoding File")
                        e_cnt += 1
                    except UnicodeEncodeError:
                        #print("Error Encoding File")
                        e_cnt += 1
                    except UnicodeError:
                        #print("General Unicode Error")
                        e_cnt += 1
                    break
    outfile.write("Text Search completed at %s.\n" % strftime("%Y-%m-%d %H:%M:%S", localtime()))
    outfile.write("Successfully processed and found %s in %d files\n" % (search_text, s_cnt))
    outfile.write("Unable to process %d files due to Unicode Encoding/Decoding Errors\n" % e_cnt)
    outfile.write("Unable to process %d files due to insufficient file permissions\n" % p_cnt)
    outfile.close()
                
if(__name__ == '__main__'):
    if(len(sys.argv) != 3):
        print("Usage: %s <Root Directory> <Search Text>" % sys.argv[0])
        sys.exit()
    else:
        search(sys.argv[1], sys.argv[2])
    